import type { Metadata } from 'next'
import { Bebas_Neue, Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Secret Santa',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-silverTree`}>
        <main className="bg-auth z-99">
          <img
            src="/images/logo__secret-santa.svg"
            alt="Secret Santa"
            className="mx-auto mb-10 w-[460px] pt-24"
          />
          <div className="mx-auto max-w-[660px]">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  )
}
