import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SecretSantaContextProvider } from '@/context/SecretSantaContext'
import '../globals.css'
import NavBar from '@/components/NavBar/NavBar'
import Nav from '@/components/SideNav/Nav'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Secret Santa',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-silverTree`}
        suppressHydrationWarning={true}
      >
        <main className="flex w-full min-w-[1600px] overflow-y-hidden bg-interior">
          <SecretSantaContextProvider>
            <div className="w-full max-w-[460px] ">
              <NavBar />
              <Nav />
              <img
                src="/images/logo__secret-santa.svg"
                alt="Secret Santa"
                className="absolute left-7 top-24 w-[347px]"
              />
            </div>
            <div className="flex w-[calc(100%-460px)] flex-col">{children}</div>
          </SecretSantaContextProvider>
        </main>
        <Footer />
      </body>
    </html>
  )
}
